### ISSUE TITLE
README support on .github

### ISSUE THREAD

**Issue by pangolp** [azerothcore/git-catalogue#101]
Currently, we have been updating many of the modules, and we have put the README.md files inside the .github folder.

This causes that the links to the modules are not loaded correctly, since they perform the query, they do not find the file and therefore, they do not show the content of the module within the catalog.

I need to check the existence of the README file in the root of the repository, and if not found, check that it is inside the .github folder.

In this way, all repositories will work correctly within the catalog.

**Comment by Helias** [comment]
solved here https://github.com/azerothcore/git-catalogue/pull/104
