### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/git-catalogue#12]
Is it the catalogue for AC (i guess so) ?

Suggestions:

- Automatically search inside the azerothcore organization forks?
- Take into account more github tags like azerothcore-module, AC-module etc can make a list if needed. At least, we will be able to ditch that shitty `core-module`

**Comment by Helias** [comment]
This is a generic configurable project which will replace the current AzerothCore catalogue.
We will allow to add/edit/delete easily the topics and tabs, moreover this new one will be really efficient compared to the old one

**Comment by BarbzYHOOL** [comment]
ok because the old one is rigid
