### ISSUE TITLE
Modules listed in the catalogue seem to have their watcher count replaced with their star count.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/git-catalogue#96]
Title. Couple examples: [mod-ptr-template](https://www.azerothcore.org/catalogue.html#/details/545080584), [catalogue](https://user-images.githubusercontent.com/38561765/215603304-e96334e8-4652-43a5-b6b3-d21ecec54a41.png) versus [Github](https://user-images.githubusercontent.com/38561765/215603481-f427b528-90e5-4d40-a475-7af0e21b8b4b.png).
[Mod-playerbots](https://www.azerothcore.org/catalogue.html#/details/472857975), [catalogue](https://user-images.githubusercontent.com/38561765/215603678-fa43b883-0425-48dc-93ad-88340b11cbda.png) versus [Github](https://user-images.githubusercontent.com/38561765/215603756-da00c0ae-7ce3-43a5-8572-fb0c59619335.png).

**Comment by Helias** [comment]
issue transfered here in the git-catalogue

**Comment by Helias** [comment]
it's weird because in the source code I can see that we use the `watchers_count` :(

![image](https://user-images.githubusercontent.com/519778/216695020-ed094946-d131-44e1-ba60-a7a48ac7b527.png)


there is some issue about API I guess

**Comment by Helias** [comment]
the API returns `4` as watchers count, it's an issue of GitHub not of the catalogue... :/ (unbelievable)

you can check it visiting the end point URL https://api.github.com/repositories/545080584

**Comment by Helias** [comment]
ooops!
ok, we should use `subscribers_count` instead of `watchers_count` it's our fault.
